import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'

export default function CreateEvent() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [name, setName] = useState('')
  const [date, setDate] = useState('')
  const [loading, setLoading] = useState(false)
  const [shareLink, setShareLink] = useState(null)
  const [error, setError] = useState(null)
  const [copied, setCopied] = useState(false)

  async function handleSubmit(e) {
    e.preventDefault()
    if (!name.trim() || !date) return

    setLoading(true)
    setError(null)

    // Create the event — token is auto-generated by Supabase via gen_random_uuid()
    const { data: event, error: eventError } = await supabase
      .from('events')
      .insert({
        name: name.trim(),
        date,
        organizer_id: user.id,
      })
      .select()
      .single()

    if (eventError) {
      setError('something went wrong. try again?')
      setLoading(false)
      return
    }

    // Add the organizer as a participant
    await supabase.from('participants').insert({
      event_id: event.id,
      name: user.user_metadata?.full_name || user.email,
      email: user.email,
      vote: null,
      is_organizer: true,
      user_id: user.id,
    })

    setShareLink(`${window.location.origin}/vote/${event.token}`)
    setLoading(false)
  }

  function copyLink() {
    navigator.clipboard.writeText(shareLink)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // --- Success state: show the shareable link ---
  if (shareLink) {
    return (
      <div
        style={{
          maxWidth: '500px',
          margin: '0 auto',
          padding: '3.5rem 1.5rem',
          textAlign: 'center',
        }}
      >
        <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🎉</div>
        <h1 style={{ color: 'var(--blue)', fontSize: '2rem', marginBottom: '0.5rem' }}>
          event created!
        </h1>
        <p
          style={{
            color: '#666',
            fontFamily: 'Poppins',
            fontSize: '0.95rem',
            marginBottom: '2rem',
            lineHeight: 1.6,
          }}
        >
          share this link with your people. they can vote without logging in.
        </p>

        <div
          style={{
            background: '#161616',
            border: '1px solid #242424',
            borderRadius: '10px',
            padding: '1.25rem',
            marginBottom: '1rem',
            wordBreak: 'break-all',
            fontFamily: 'Poppins',
            fontSize: '0.875rem',
            color: '#888',
            textAlign: 'left',
          }}
        >
          {shareLink}
        </div>

        <button
          onClick={copyLink}
          style={{
            background: copied ? '#1a3035' : 'var(--blue)',
            color: copied ? 'var(--blue)' : 'var(--black)',
            border: copied ? '1px solid var(--blue)' : 'none',
            padding: '0.9rem',
            borderRadius: '8px',
            fontFamily: 'Nunito',
            fontWeight: 900,
            fontSize: '1rem',
            cursor: 'pointer',
            width: '100%',
            marginBottom: '1rem',
            transition: 'all 0.15s',
          }}
        >
          {copied ? '✓ link copied!' : 'copy link'}
        </button>

        <button
          onClick={() => navigate('/dashboard')}
          style={{
            background: 'transparent',
            color: '#555',
            border: 'none',
            fontFamily: 'Poppins',
            fontSize: '0.875rem',
            cursor: 'pointer',
          }}
        >
          ← back to dashboard
        </button>
      </div>
    )
  }

  // --- Form ---
  return (
    <div style={{ maxWidth: '500px', margin: '0 auto', padding: '2.5rem 1.5rem' }}>
      <button
        onClick={() => navigate('/dashboard')}
        style={{
          background: 'transparent',
          color: '#555',
          border: 'none',
          fontFamily: 'Poppins',
          fontSize: '0.875rem',
          cursor: 'pointer',
          marginBottom: '2rem',
          padding: 0,
        }}
      >
        ← back
      </button>

      <h1 style={{ color: 'var(--blue)', fontSize: '2rem', marginBottom: '0.4rem' }}>
        new event
      </h1>
      <p
        style={{
          color: '#666',
          fontFamily: 'Poppins',
          fontSize: '0.9rem',
          marginBottom: '2rem',
        }}
      >
        fill in the details. we'll handle the existential dread.
      </p>

      <form
        onSubmit={handleSubmit}
        style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}
      >
        <div>
          <label
            style={{
              display: 'block',
              fontFamily: 'Poppins',
              fontSize: '0.8rem',
              color: '#666',
              marginBottom: '0.4rem',
            }}
          >
            event name
          </label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="trivia night, dinner with the squad..."
            required
            style={{
              width: '100%',
              background: '#161616',
              border: '1px solid #242424',
              borderRadius: '8px',
              padding: '0.8rem 1rem',
              color: 'var(--white)',
              fontFamily: 'Poppins',
              fontSize: '1rem',
              outline: 'none',
            }}
          />
        </div>

        <div>
          <label
            style={{
              display: 'block',
              fontFamily: 'Poppins',
              fontSize: '0.8rem',
              color: '#666',
              marginBottom: '0.4rem',
            }}
          >
            date
          </label>
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            required
            style={{
              width: '100%',
              background: '#161616',
              border: '1px solid #242424',
              borderRadius: '8px',
              padding: '0.8rem 1rem',
              color: 'var(--white)',
              fontFamily: 'Poppins',
              fontSize: '1rem',
              outline: 'none',
              colorScheme: 'dark',
            }}
          />
        </div>

        {error && (
          <p style={{ color: '#ff6b6b', fontFamily: 'Poppins', fontSize: '0.875rem' }}>
            {error}
          </p>
        )}

        <button
          type="submit"
          disabled={loading}
          style={{
            background: 'var(--blue)',
            color: 'var(--black)',
            border: 'none',
            padding: '0.9rem',
            borderRadius: '8px',
            fontFamily: 'Nunito',
            fontWeight: 900,
            fontSize: '1rem',
            cursor: loading ? 'not-allowed' : 'pointer',
            opacity: loading ? 0.65 : 1,
            marginTop: '0.25rem',
          }}
        >
          {loading ? 'creating...' : 'create event →'}
        </button>
      </form>
    </div>
  )
}
